/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author hp
 */
public final class DataSignUp extends javax.swing.JFrame {

    /**
     * Creates new form DataSignUp
     */
    public DataSignUp() throws SQLException{
        initComponents();
        loading();
        c1.setSelected(false);
        d2.setEnabled(false);
        d1.setDate(new Date());        
        d2.setDate(new Date());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        doctable = new javax.swing.JTable();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        d2 = new com.toedter.calendar.JDateChooser();
        d1 = new com.toedter.calendar.JDateChooser();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        c1 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        b4 = new javax.swing.JButton();
        t15 = new javax.swing.JTextField();
        b5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1250, 700));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        doctable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Tel Number", "Date", "Amount Paid", "Re Date", "Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        doctable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(doctable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 1210, 310));

        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t1KeyTyped(evt);
            }
        });
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 150, -1));

        t2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t2KeyTyped(evt);
            }
        });
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 150, -1));

        t3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t3KeyTyped(evt);
            }
        });
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 150, -1));

        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });
        t4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t4KeyReleased(evt);
            }
        });
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 250, -1));

        l1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 255));
        l1.setText("Name");
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, 20));

        l2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 255, 255));
        l2.setText("Tel number");
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, 20));

        l3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 255, 255));
        l3.setText("Date");
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, 20));

        l4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        l4.setForeground(new java.awt.Color(255, 255, 255));
        l4.setText("Amount paid");
        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, 20));

        l5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        l5.setForeground(new java.awt.Color(255, 255, 255));
        l5.setText("Date of revision");
        getContentPane().add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, -1, 20));

        l6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        l6.setForeground(new java.awt.Color(255, 255, 255));
        l6.setText("Search");
        getContentPane().add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, 20));

        d2.setDateFormatString("yyyy-MM-dd");
        d2.setEnabled(false);
        d2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                d2KeyTyped(evt);
            }
        });
        getContentPane().add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, 150, -1));

        d1.setDateFormatString("yyyy-MM-dd");
        d1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                d1KeyTyped(evt);
            }
        });
        getContentPane().add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 150, -1));

        b1.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        b1.setText("Add");
        b1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b1MouseExited(evt);
            }
        });
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 640, 100, 30));

        b2.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        b2.setText("Update");
        b2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        b2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b2MouseExited(evt);
            }
        });
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 640, 100, 30));

        b3.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        b3.setText("Remve");
        b3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        b3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b3MouseExited(evt);
            }
        });
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 640, 100, 30));

        c1.setBackground(new java.awt.Color(0, 0, 0));
        c1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        c1.setForeground(new java.awt.Color(255, 255, 255));
        c1.setText("Is there any revision?");
        c1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c1MouseClicked(evt);
            }
        });
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 180, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/icons8-macos-close-32.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, -1, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/icons8-macos-minimize-32.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 0, 30, 40));

        b4.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        b4.setText("Caculater -->");
        b4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b4MouseExited(evt);
            }
        });
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 240, 120, 30));

        t15.setText("There is no.");
        getContentPane().add(t15, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 120, 0, -1));

        b5.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        b5.setText("Clear");
        b5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        b5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b5MouseExited(evt);
            }
        });
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        getContentPane().add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 640, 100, 30));
        b5.getAccessibleContext().setAccessibleName("Clear\n");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/talbe.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 700));

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 640, 0, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4ActionPerformed

    private void t4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t4KeyReleased
        // TODO add your handling code here:
        DefaultTableModel smodel=(DefaultTableModel) doctable.getModel();
        String Search = t4.getText().toLowerCase();
        TableRowSorter<DefaultTableModel> tr =new TableRowSorter<DefaultTableModel>(smodel);
        doctable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(Search));

    }//GEN-LAST:event_t4KeyReleased

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void b1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseEntered
        // TODO add your handling code here:
        b1.setBackground(Color.black);
        b1.setForeground(Color.white);
    }//GEN-LAST:event_b1MouseEntered

    private void b1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseExited
        // TODO add your handling code here:
        b1.setBackground(Color.white);
        b1.setForeground(Color.black);
    }//GEN-LAST:event_b1MouseExited

    private void b2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseEntered
        // TODO add your handling code here:
        b2.setBackground(Color.black);
        b2.setForeground(Color.white);
    }//GEN-LAST:event_b2MouseEntered

    private void b2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseExited
        // TODO add your handling code here:
        b2.setBackground(Color.white);
        b2.setForeground(Color.black);
    }//GEN-LAST:event_b2MouseExited

    private void b3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MouseEntered
        // TODO add your handling code here:
        b3.setBackground(Color.red);
        b3.setForeground(Color.white);
    }//GEN-LAST:event_b3MouseEntered

    private void b3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MouseExited
        // TODO add your handling code here:
        b3.setBackground(Color.white);
        b3.setForeground(Color.black);
    }//GEN-LAST:event_b3MouseExited

    private void b1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseClicked
        // TODO add your handling code here:
       DefaultTableModel smodel=(DefaultTableModel) doctable.getModel();
       SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
       String date = dFormat.format(d1.getDate());
       SimpleDateFormat tFormat = new SimpleDateFormat("yyyy-MM-dd");
       String date2 = tFormat.format(d2.getDate());
       if(t15.isVisible()){
       smodel.addRow(new Object[]{t1.getText(),t2.getText(),date,t3.getText(),t15.getText()});} 
       else{
       smodel.addRow(new Object[]{t1.getText(),t2.getText(),date,t3.getText(),date2});}
       //adding
       String username = "root";
       String password = "123456";
       String url = "jdbc:mysql://localhost:3306/patient";
       try(Connection connect = DriverManager.getConnection(url,username,password)){
           System.out.println("Data base is Connected");
           String sql="insert into patdata (name,phone,date,amount,rep)"+" values (?,?,?,?,?)";
           PreparedStatement stm = connect.prepareStatement(sql);
           stm.setString(1, t1.getText());
           stm.setInt(2, Integer.parseInt(t2.getText()));
           stm.setString(3, date);
           stm.setInt(4, Integer.parseInt(t3.getText()));
           stm.setString(5, date2);
           stm.execute();
           clear();
       }
       catch (SQLException ex) {Logger.getLogger(DataSignUp.class.getName()).log(Level.SEVERE, null, ex);}
    }//GEN-LAST:event_b1MouseClicked

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_b1ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.setState(DataSignUp.ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void b4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MouseEntered
        // TODO add your handling code here:
        b4.setBackground(Color.blue);
        b4.setForeground(Color.white);
    }//GEN-LAST:event_b4MouseEntered

    private void b4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MouseExited
        // TODO add your handling code here:
       b4.setBackground(Color.white);
       b4.setForeground(Color.black);
    }//GEN-LAST:event_b4MouseExited

    private void b4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MouseClicked
        // TODO add your handling code here:
        new calculater_1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b4MouseClicked

    private void c1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c1MouseClicked
       // TODO add your handling code here:
       if(c1.isSelected()){
          d2.setEnabled(true);
          t15.setVisible(false);
        try {
            String date3 = "2022-01-01";
            Date date4 = new SimpleDateFormat("yyyy-MM-dd").parse(date3);
            d2.setDate(date4);}
        catch (Exception e) {
            System.out.println(e);}}
       else{
       d2.setEnabled(false);
       t15.setVisible(true);       
       }
    }//GEN-LAST:event_c1MouseClicked

    private void t1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_t1KeyTyped

    private void t2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t2KeyTyped
        // TODO add your handling code here:
           // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_t2KeyTyped

    private void d1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_d1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_d1KeyTyped

    private void t3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t3KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c)){
        evt.consume();
        }
    }//GEN-LAST:event_t3KeyTyped

    private void d2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_d2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_d2KeyTyped

    private void b2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseClicked
        // TODO add your handling code here:
         DefaultTableModel smodel=(DefaultTableModel) doctable.getModel();
         SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
         String date = dFormat.format(d1.getDate());
         SimpleDateFormat tFormat = new SimpleDateFormat("yyyy-MM-dd");
         String date2 = tFormat.format(d2.getDate());
//         update
  String username = "root";
       String password = "123456";
       String url = "jdbc:mysql://localhost:3306/patient";
       try(Connection connect = DriverManager.getConnection(url,username,password)){
           System.out.println("Data base is Connected");
           String sql="update patdata set name=? , phone=? , date=? , amount=? , rep=? where id=?";
           PreparedStatement stm = connect.prepareStatement(sql);
           stm.setString(1, t1.getText());
           stm.setInt(2, Integer.parseInt(t2.getText()));
           stm.setString(3, date);
           stm.setInt(4, Integer.parseInt(t3.getText()));
           stm.setString(5, date2);
           stm.setInt(6, Integer.parseInt(doctable.getValueAt(doctable.getSelectedRow(), 5).toString()));
           stm.execute();
       }
       catch (SQLException ex) {Logger.getLogger(DataSignUp.class.getName()).log(Level.SEVERE, null, ex);}
         smodel.setValueAt(t1.getText(), doctable.getSelectedRow(), 0);
         smodel.setValueAt(t2.getText(), doctable.getSelectedRow(), 1);
         smodel.setValueAt(t3.getText(), doctable.getSelectedRow(), 3);
         smodel.setValueAt(date, doctable.getSelectedRow(), 2);
         if(t15.isVisible()){
         smodel.setValueAt(t15.getText(), doctable.getSelectedRow(), 4);} 
         else{smodel.setValueAt(date2, doctable.getSelectedRow(), 4);}
         clear();
    }//GEN-LAST:event_b2MouseClicked

    private void b3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MouseClicked
        // TODO add your handling code here:
         DefaultTableModel smodel=(DefaultTableModel) doctable.getModel();
           String username = "root";
       String password = "123456";
       String url = "jdbc:mysql://localhost:3306/patient";
       try(Connection connect = DriverManager.getConnection(url,username,password)){
           System.out.println("Data base is Connected");
           String sql="delete from patdata where id =?";
           PreparedStatement stm = connect.prepareStatement(sql);
           stm.setInt(1, Integer.parseInt(doctable.getValueAt(doctable.getSelectedRow(), 5).toString()));
           stm.execute();}
       catch (SQLException ex) {Logger.getLogger(DataSignUp.class.getName()).log(Level.SEVERE, null, ex);}
       smodel.removeRow(doctable.getSelectedRow());
       clear();        
    }//GEN-LAST:event_b3MouseClicked

    private void doctableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctableMouseClicked
        // TODO add your handling code here:
         DefaultTableModel smodel=(DefaultTableModel) doctable.getModel();
         t1.setText(smodel.getValueAt(doctable.getSelectedRow(), 0).toString());
         t2.setText(smodel.getValueAt(doctable.getSelectedRow(), 1).toString());
         t3.setText(smodel.getValueAt(doctable.getSelectedRow(), 3).toString());
         id.setText(smodel.getValueAt(doctable.getSelectedRow(), 5).toString());
//        try {
//            int index = doctable.getSelectedRow();
//            Date date;
//               date = new SimpleDateFormat("yyyy-MM-dd").parse((String)smodel.getValueAt(index, 2));
//                    d1.setDate(date);
//                    } catch (ParseException ex) {
////            Logger.getLogger(DataSignUp.class.getName()).log(Level.SEVERE, null, ex);
////        } 
//        if(t15.isVisible()){
//           t15.setText(smodel.getValueAt(doctable.getSelectedRow(), 4).toString());
//        }
//        else{
//        try {
//            int index = doctable.getSelectedRow();
//            Date date;
//               date = new SimpleDateFormat("yyyy-MM-dd").parse((String)smodel.getValueAt(index, 4));
//                    d2.setDate(date);
//                    } catch (ParseException ex) {
//            Logger.getLogger(DataSignUp.class.getName()).log(Level.SEVERE, null, ex);}
//        }
    }//GEN-LAST:event_doctableMouseClicked

    private void b5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5MouseClicked
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_b5MouseClicked

    private void b5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5MouseEntered
        // TODO add your handling code here:
        b5.setBackground(Color.black);
        b5.setForeground(Color.white);
    }//GEN-LAST:event_b5MouseEntered

    private void b5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5MouseExited
        // TODO add your handling code here:
        b5.setBackground(Color.white);
        b5.setForeground(Color.black);
    }//GEN-LAST:event_b5MouseExited

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5ActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    /**
     *
     */
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DataSignUp().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(DataSignUp.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    /**
     *
     */
    public void  clear(){
        t1.setText("");
        t2.setText("");
        t3.setText("");
        d1.setDate(new Date());
        d2.setDate(new Date());
    }
   public void loading() {
       String username = "root";
       String password = "123456";
       String url = "jdbc:mysql://localhost:3306/patient";
       try(Connection connect = DriverManager.getConnection(url,username,password)){
           System.out.println("Data base is Connected");
       String sql="select name,phone,date,amount,rep,id from patdata";
       Statement stm = connect.createStatement();
       ResultSet rs;
       rs = stm.executeQuery(sql);
       while(rs.next()){
        DefaultTableModel smodel=(DefaultTableModel) doctable.getModel();
        smodel.addRow(new Object[]{rs.getString("name"),rs.getInt("phone"),
            rs.getDate("date"),rs.getInt("amount"),rs.getDate("rep"),rs.getString("id")});
       }    
       } catch (SQLException ex) {
            Logger.getLogger(DataSignUp.class.getName()).log(Level.SEVERE, null, ex);
       }
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JCheckBox c1;
    private com.toedter.calendar.JDateChooser d1;
    private com.toedter.calendar.JDateChooser d2;
    private javax.swing.JTable doctable;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t15;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    // End of variables declaration//GEN-END:variables
}
